import { definePrefabKnowledge } from '@dsl/knowledge'

export default definePrefabKnowledge((utils) => {
  utils.name('graph')
  utils.description('A visual graph data structure supporting directed/undirected and weighted graphs. Includes BFS/DFS traversal, shortest path, and MST visualization.')
  
  utils.prop('nodes').describe('Array of node identifiers or objects with id and optional label.').type('(string | number | { id: string | number, label?: string })[]')
  utils.prop('edges').describe('Array of edges. Each edge has from, to, and optional weight.').type('{ from: string | number, to: string | number, weight?: number }[]')
  utils.prop('directed').describe('Whether the graph is directed.').type('boolean').optional('false')
  utils.prop('weighted').describe('Whether to show edge weights.').type('boolean').optional('false')
  utils.prop('layout').describe('Layout algorithm for node positioning.').type('"force" | "circular" | "hierarchical" | "grid"').optional('"force"')
  utils.prop('highlightNodes').describe('Array of node IDs to highlight.').type('(string | number)[]').optional('[]')
  utils.prop('highlightEdges').describe('Array of edge pairs to highlight.').type('[string | number, string | number][]').optional('[]')
  utils.prop('highlightColor').describe('Color for highlighted elements.').type('string').optional('"warning"')
  utils.prop('current').describe('Currently active node ID.').type('string | number').optional()
  utils.prop('currentColor').describe('Color for current node.').type('string').optional('"primary"')
  utils.prop('visited').describe('Array of visited node IDs.').type('(string | number)[]').optional('[]')
  utils.prop('visitedColor').describe('Color for visited nodes.').type('string').optional('"secondary"')
  utils.prop('path').describe('Array of node IDs forming a path.').type('(string | number)[]').optional('[]')
  utils.prop('pathColor').describe('Color for path nodes and edges.').type('string').optional('"success"')
  utils.prop('queue').describe('Array of node IDs in BFS queue (shown separately).').type('(string | number)[]').optional('[]')
  utils.prop('stack').describe('Array of node IDs in DFS stack (shown separately).').type('(string | number)[]').optional('[]')
  utils.prop('distances').describe('Object mapping node IDs to distances (for Dijkstra).').type('Record<string | number, number>').optional('{}')
  utils.prop('x').describe('X position of graph on canvas.').type('number').optional('0')
  utils.prop('y').describe('Y position of graph on canvas.').type('number').optional('0')
  utils.prop('width').describe('Width of graph area.').type('number').optional('400')
  utils.prop('height').describe('Height of graph area.').type('number').optional('300')
  utils.prop('nodeRadius').describe('Radius of graph nodes.').type('number').optional('25')
  utils.prop('label').describe('Label text above the graph.').type('string').optional()
})
